name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm i

      - name: Build Astro
        run: pnpm run build

      - name: Deno deploy
        uses: denoland/deployctl@v1
        with:
          project: fresh-dove-66
          entrypoint: server/entry.mjs
          root: dist
