name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clonse repository
        uses: actions/checkout@v3

      - name: Instal dependencies
        run: pnpm i

      - name: Build Astro
        run: pnpm run build

      - name: Deno deploy
        uses: denoland/deployctl@v1
        with:
          project: sncalvo.github.io
          entrypoint: server/entry.mjs
          root: dist
